<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RootElement" nsURI="http:///RootElement.ecore" nsPrefix="RootElement">
  <eClassifiers xsi:type="ecore:EClass" name="LIFFDocument">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="LIFF Document"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcLang" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trgLang" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" ordered="false" lowerBound="1"
        upperBound="-1" eType="#//file" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_moduleorextensionattributes"
        ordered="false" lowerBound="1" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="*module or extension attributes"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="file">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype1" ordered="false"
        lowerBound="1" eType="#//skeleton" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" ordered="false"
        upperBound="-1" eType="#//group" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="skeleton"/>
  <eClassifiers xsi:type="ecore:EClass" name="group"/>
</ecore:EPackage>
